"use client";

const S = {
  page: { minHeight: "100vh", background: "#FAFAF9", color: "#1a1a1a", fontFamily: "'DM Sans', -apple-system, sans-serif" },
  header: { borderBottom: "1px solid #ECEAE6", background: "#FAFAF9", position: "sticky", top: 0, zIndex: 50 },
  headerInner: { maxWidth: 720, margin: "0 auto", padding: "0 20px", display: "flex", alignItems: "center", justifyContent: "space-between", height: 60 },
  logo: { display: "flex", alignItems: "center", gap: 10, textDecoration: "none" },
  logoText: { fontWeight: 600, fontSize: 15, color: "#1a1a1a" },
  back: { fontSize: 13, color: "#888", textDecoration: "none" },
  body: { maxWidth: 720, margin: "0 auto", padding: "40px 20px 96px" },
  banner: { background: "#FFFBEB", border: "1px solid #FDE68A", borderRadius: 10, padding: "14px 18px", fontSize: 13, color: "#92600A", lineHeight: 1.6, marginBottom: 32 },
  h1: { fontSize: 26, fontWeight: 700, letterSpacing: "-0.4px", margin: "0 0 6px" },
  updated: { fontSize: 13, color: "#aaa", marginBottom: 36 },
  h2: { fontSize: 17, fontWeight: 600, margin: "36px 0 12px" },
  p: { fontSize: 14, color: "#444", lineHeight: 1.75, margin: "0 0 14px" },
  ul: { fontSize: 14, color: "#444", lineHeight: 1.75, margin: "0 0 14px", paddingLeft: 20 },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13, margin: "0 0 20px" },
  th: { textAlign: "left", padding: "8px 10px", borderBottom: "1.5px solid #E8E8E4", color: "#888", fontWeight: 600, fontSize: 12, textTransform: "uppercase", letterSpacing: "0.04em" },
  td: { padding: "10px 10px", borderBottom: "1px solid #F0EFEB", color: "#444", verticalAlign: "top" },
  placeholder: { background: "#FEF3C7", padding: "0 4px", borderRadius: 3 },
};

function Shell({ children }) {
  return (
    <div style={S.page}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&display=swap'); * { box-sizing: border-box; } body { margin: 0; }`}</style>
      <header style={S.header}>
        <div style={S.headerInner}>
          <a href="/" style={S.logo}>
            <img src="/logo-mark.png" alt="Cruiser Meets" style={{ height: 28, width: "auto" }} />
            <span style={S.logoText}>Cruiser Meets</span>
          </a>
          <a href="/" style={S.back}>Back to home</a>
        </div>
      </header>
      <div style={S.body}>{children}</div>
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <Shell>
      <div style={S.banner}>
        <strong>Draft document.</strong> This is a starting-point Privacy Policy written for launch, not a substitute for review by a qualified attorney or privacy professional. Have it reviewed — especially if you have users in the EU/UK (GDPR), California (CCPA/CPRA), or other jurisdictions with specific data-privacy requirements — before relying on it.
      </div>

      <h1 style={S.h1}>Privacy Policy</h1>
      <div style={S.updated}>Last updated: August 25, 2026</div>

      <h2 style={S.h2}>1. Information we collect</h2>
      <p style={S.p}>We collect information you provide directly, and some information generated by using the service:</p>
      <table style={S.table}>
        <thead>
          <tr><th style={S.th}>Category</th><th style={S.th}>Examples</th></tr>
        </thead>
        <tbody>
          <tr>
            <td style={S.td}>Account info</td>
            <td style={S.td}>Email address, and if you sign in with Google, your Google account identifier.</td>
          </tr>
          <tr>
            <td style={S.td}>Profile info</td>
            <td style={S.td}>Username, bio, city/state, social links — all optional beyond username.</td>
          </tr>
          <tr>
            <td style={S.td}>Location data</td>
            <td style={S.td}>Cities, zip codes, or addresses you enter when searching for or submitting a Meet, and the approximate coordinates we derive from them via a geocoding service to power maps and radius search.</td>
          </tr>
          <tr>
            <td style={S.td}>Photos &amp; media</td>
            <td style={S.td}>Meet flyers/photos, profile photos and banners, vehicle photos, and post photos/videos you upload.</td>
          </tr>
          <tr>
            <td style={S.td}>Content</td>
            <td style={S.td}>Comments, replies, posts, vehicle and mod details, RSVPs, and reports you submit.</td>
          </tr>
          <tr>
            <td style={S.td}>Usage data</td>
            <td style={S.td}>Basic technical data generated by using the site (e.g. session tokens stored in your browser to keep you signed in).</td>
          </tr>
        </tbody>
      </table>

      <h2 style={S.h2}>2. How we use it</h2>
      <ul style={S.ul}>
        <li>To operate core features: authentication, listing and searching Meets, profiles, comments, RSVPs, and the garage/mod system</li>
        <li>To show approximate distance between you and a Meet when you search by location</li>
        <li>To review submitted Meets and reported content for moderation purposes</li>
        <li>To communicate with you about your account or submissions</li>
      </ul>
      <p style={S.p}>We do not sell your personal information.</p>

      <h2 style={S.h2}>3. Who we share it with</h2>
      <p style={S.p}>We use a small number of service providers to run Cruiser Meets, who process data on our behalf:</p>
      <ul style={S.ul}>
        <li><strong>Supabase</strong> — authentication, database, and file storage for photos and other media</li>
        <li><strong>Google</strong> — if you choose to sign in with Google</li>
        <li><strong>OpenStreetMap / Nominatim</strong> — converts the city, zip, or address you enter into map coordinates</li>
      </ul>
      <p style={S.p}>
        Your username, profile info, comments, posts, and vehicle info are visible to other users and, in most cases, to anyone visiting the site — Cruiser Meets profiles and Meet listings are public by design. We don't share your email address publicly.
      </p>

      <h2 style={S.h2}>4. Your choices</h2>
      <ul style={S.ul}>
        <li>You can edit or remove most profile information, vehicles, posts, and comments yourself at any time</li>
        <li>You can request deletion of your account and associated data by contacting us</li>
        <li>You can report content you believe violates our guidelines from any comment, post, or vehicle photo</li>
      </ul>

      <h2 style={S.h2}>5. Data retention</h2>
      <p style={S.p}>
        We keep your information for as long as your account is active, or as needed to provide the service. If you delete your account, we remove or anonymize your personal data within a reasonable time, except where we're required to retain it for legal or safety reasons. <span style={S.placeholder}>[A legal reviewer should confirm a specific retention period if one is required in your jurisdiction.]</span>
      </p>

      <h2 style={S.h2}>6. Children's privacy</h2>
      <p style={S.p}>
        Cruiser Meets is not directed at children under 13, and we don't knowingly collect information from them. <span style={S.placeholder}>[Confirm this age threshold matches your Terms of Service and any applicable law.]</span>
      </p>

      <h2 style={S.h2}>7. Security</h2>
      <p style={S.p}>
        We use reasonable technical measures to protect your information, but no method of storage or transmission is 100% secure, and we can't guarantee absolute security.
      </p>

      <h2 style={S.h2}>8. Changes to this policy</h2>
      <p style={S.p}>
        We may update this policy as Cruiser Meets evolves. Material changes will be reflected by updating the "Last updated" date above.
      </p>

      <h2 style={S.h2}>9. Contact</h2>
      <p style={S.p}>
        Questions about this policy, or requests to access or delete your data, can be sent to <span style={S.placeholder}>[insert contact email]</span>.
      </p>
    </Shell>
  );
}
